apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-voloume
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Mi
  hostPath:
    path: /opt/volume/nginx

  awsElasticBlockStore:
    volumeID: <volume-ID>
    fsType: ext4