apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-log
spec:
  accessModes:
    - ReadWriteMany/ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: /pv/log

  awsElasticBlockStore:
    volumeID: <volume-ID>
    fsType: ext4