apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
    - name: event-simulator
      image: kodekloud/event-simulator
      env:
        - name: log_handlers
          value: file
      volumeMounts:
        - mountPath: /log
          name: log-volume

  volumes:
    - name: log-voloume
      hostPath:
        path: /var/log/webapp
        type: directory