apiVersion: v1
kind: Pod
metadata:
  name: elephant
  labels:
    app: elephant
spec:
  containers:
    - name: elephant
      image: polinux/stress
      ports:
        - containerPort: 8080
      resources:
        requests:
          memory: "15Mi"
          cpu: 1
        limits:
          memory: "20Mi"
          cpu: 2
