apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: httpd-frontend
          image: httpd:2.4-alpine
    replicas: 3
    selector:
      matchLabels:
        type: front-end
