apiVersion: v1
kind: Service
metadata:
  - name: webapp-service

spec:
  type: NodePort
  ports:
    - targetPort: 8080 #TargetPort to Service
      port: 8080 # Service Port
      nodePort: 30080 # NodePort
  selector:
    app: simple-webapp
    type: front-end

