apiVersion: batch/v1
kind: Pod
metadata:
  name: math-add-job
spec:
  completeions: 3
  parallelism: 3
  template:
    spec:
      containers:
        - name: math-add
          image: ubuntu
          command: ['expr','3','+','2']
      restartPolicy: Never
