apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: google-storage
  capacity:
    storage: 500Mi
  # Static Provisioning by creating a volume in gce
  gcePersistentDisk:
    pdName: pd-disk
    fsType: ext4