apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-2
  labels:
    name: simple-webapp-2
spec:
  containers:
    - name: simple-webapp-2
      image: kodekloud/webapp-delayed-start
      ports:
        - containerPort: 8080
#
      livenessProbe:
        httpGet:
          path: /live
          port: 8080

        initialDelaySeconds: 80
        periodSeconds: 1

#DB readiness
      livenessProbe:
        tcpSocket:
          port: 3306

#container Readiness

      livenessProbe:
        exec:
          command:
            - cat
            - /app/is_healthy